### ISSUE TITLE
疑惑

### ISSUE THREAD

**Issue by WavesLi** [yongzhuo/Qwen-SFT#1]
看到QLORA配置的可lora训练网络单元参数为["c_attn","c_proj"] ,请问是因为Qwen lora的训练只能在这两个名称网络单元训练吗，还是能扩配置更多名称的网络单元，例如在对llama2的QLORA训练时可以配置的参数为lora_trainable="q_proj,v_proj,k_proj,o_proj,gate_proj,down_proj,up_proj"
modules_to_save="embed_tokens,lm_head"。望您不吝赐教

**Comment by yongzhuo** [comment]
qwen的layer_name命名问题，'transformer.wte.weight'
'transformer.h.0.ln_1.weight'
'transformer.h.0.attn.c_attn.weight'
'transformer.h.0.attn.c_attn.bias'
'transformer.h.0.attn.c_proj.weight'
'transformer.h.0.ln_2.weight'
'transformer.h.0.mlp.w1.weight'
'transformer.h.0.mlp.w2.weight'
'transformer.h.0.mlp.c_proj.weight'
...
'transformer.ln_f.weight'
'lm_head.weight'
