### ISSUE TITLE
有人成功复现了吗

### ISSUE THREAD

**Issue by yyy4444** [yongzhuo/Qwen-SFT#3]

**Comment by whysirier** [comment]
'QWenConfig' object has no attribute 'padded_vocab_size'

**Comment by yongzhuo** [comment]
这个是刚出来的版本，后边config.json, model_qwen.py都大改不一致了，看看有没有时间再改改
你的依赖不要用该源码自带的
from qwen_sft.models.qwen.modeling_qwen import QWenLMHeadModel as LLMModel
from qwen_sft.models.qwen.tokenization_qwen import QWenTokenizer as LLMTokenizer
from qwen_sft.models.qwen.configuration_qwen import QWenConfig as LLMConfig

用qwen最新的应该可以
