### ISSUE TITLE
推理输入输出(assistant\n放置位置不同)，这是为什么呀？

### ISSUE THREAD

**Issue by jack12356** [yongzhuo/Qwen-SFT#4]
推理输入输出(assistant\n放置位置不同)，这是为什么呀？看代码没看出来，这个有什么依据吗？

**Comment by yongzhuo** [comment]
一般推理都会带assistant\n，类似user\nxxx\n\nassistant\n；微调不mask其实也行，这只是是不是参与loss计算的问题。这里这么做是看起来自然一点，问题 和 答案的界限区分明显一些
